name: DeployToProd

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          git submodule init
          git submodule update --init --recursive
          ls infrastructure
          ls website
