name: DeployToProd

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out repository and recursively initialize submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive
    
      # List files in submodules as a sanity check
      - name: List files in submdodules
        run: |
          ls infrastructure
          ls website
     
      # Set up node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
       
      # Build website code
      - name: Build website
        run: |
          cd website
          npm install
          npm run build
      
      # Build infrastructure code
      - name: Build infrastructure
        run: |
          cd infrastructure
          npm install
          npm run build
      
      # List build files as a sanity check
      - name: List build files
        run: |
          ls website/build
          
      # Set up CDK
      - name: Set Up CDK
        run: npm install -g aws-cdk

      # Synthesize CDK
      - name: Synth CDK
        run: |
          cd infrastructure
          cdk synth --region ${{ secrets.AWS_REGION }} --targetAccount ${{ secrets.AWS_ACCOUNT_ID }} --output build/cdk.out
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_TARGET_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
